# Generated by Django 4.2.3 on 2025-05-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
