# Generated by Django 4.2.3 on 2025-05-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ruleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
